/// Pipeline barrier types for GPU synchronization and layout transitions.
///
/// These types describe memory dependencies and image layout transitions
/// between pipeline stages. Used by the render graph compiler to insert
/// barriers automatically based on resource access patterns.

use std::sync::Arc;
use bitflags::bitflags;
use super::render_pass::ImageLayout;
use super::texture::Texture;

bitflags! {
    /// Pipeline stage flags — which stages of the GPU pipeline are involved.
    ///
    /// Values mirror Vulkan VkPipelineStageFlagBits for zero-cost conversion.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct PipelineStageFlags: u32 {
        const TOP_OF_PIPE             = 0x0000_0001;
        const VERTEX_SHADER           = 0x0000_0008;
        const FRAGMENT_SHADER         = 0x0000_0080;
        const EARLY_FRAGMENT_TESTS    = 0x0000_0100;
        const LATE_FRAGMENT_TESTS     = 0x0000_0200;
        const COLOR_ATTACHMENT_OUTPUT = 0x0000_0400;
        const COMPUTE_SHADER          = 0x0000_0800;
        const TRANSFER                = 0x0000_1000;
        const BOTTOM_OF_PIPE          = 0x0000_2000;
        const RAY_TRACING_SHADER      = 0x0020_0000;
    }
}

bitflags! {
    /// Access flags — what type of memory operation is performed.
    ///
    /// Values mirror Vulkan VkAccessFlagBits for zero-cost conversion.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct AccessFlags: u32 {
        const SHADER_READ            = 0x0000_0020;
        const SHADER_WRITE           = 0x0000_0040;
        const COLOR_ATTACHMENT_READ  = 0x0000_0080;
        const COLOR_ATTACHMENT_WRITE = 0x0000_0100;
        const DEPTH_STENCIL_READ     = 0x0000_0200;
        const DEPTH_STENCIL_WRITE    = 0x0000_0400;
        const TRANSFER_READ          = 0x0000_0800;
        const TRANSFER_WRITE         = 0x0000_1000;
    }
}

/// Image memory barrier — describes a layout transition and memory dependency for an image.
///
/// Generated by the render graph compiler and emitted by `CommandList::pipeline_barrier()`.
pub struct ImageMemoryBarrier {
    /// Source pipeline stage (what must complete before the barrier)
    pub src_stage: PipelineStageFlags,
    /// Destination pipeline stage (what waits for the barrier)
    pub dst_stage: PipelineStageFlags,
    /// Source access mask (what memory operations to flush)
    pub src_access: AccessFlags,
    /// Destination access mask (what memory operations to invalidate for)
    pub dst_access: AccessFlags,
    /// Current image layout
    pub old_layout: ImageLayout,
    /// Target image layout after the barrier
    pub new_layout: ImageLayout,
    /// The GPU texture to transition
    pub texture: Arc<dyn Texture>,
    /// Base array layer
    pub base_layer: u32,
    /// Number of array layers
    pub layer_count: u32,
    /// Base mip level
    pub base_mip_level: u32,
    /// Number of mip levels
    pub mip_count: u32,
}
